name: nebula_mesh_toolkit
description: CLI toolkit and configuration helper for Nebula mesh/overlay networks.
version: 0.1.0
repository: https://github.com/agilord/nebula_mesh_toolkit
topics:
  - cli
  - tool
  - network
  - configuration
  - nebula

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.2
  json_annotation: ^4.9.0
  yaml_edit: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^4.0.0
  json_serializable: ^6.9.0
  test: ^1.24.0
